name: Publish Docker image

on:
  schedule:
    - cron: '41 16 27 * *' # 04:41 PM on the 27th of every month
  push:
    branches:
      - "main"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REPOSITORY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          Platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
          push: true
          tags: |
            ${{ vars.REPOSITORY }}:latest
